name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/checkout@v4
        with:
          repository: 'mccahan/HomeSpan'
          path: libraries/HomeSpan

      - run: pip install esptool
      - name: Install Arduino CLI
        uses: arduino/setup-arduino-cli@v1

      - name: Install platform
        run: |
          ARDUINO_LIBRARY_ENABLE_UNSAFE_INSTALL=true arduino-cli lib install --git-url https://github.com/mccahan/HomeSpan.git
          arduino-cli core update-index
          arduino-cli core install esp32:esp32
      
      - run: arduino-cli lib list

      # Finally, we compile the sketch, using the FQBN that was set
      # in the build matrix.
      - name: Compile Sketch
        run: arduino-cli compile -e --fqbn esp32:esp32:esp32 --build-path build/ ./05-WorkingLED

      - run: find . -name '*.bin'
      - name: Set Boot App0 Path
        run: |
          BOOT_APP0_PATH=$(find /home/runner -type f -name boot_app0.bin)
          echo "BOOT_APP0_PATH=$BOOT_APP0_PATH" >> $GITHUB_ENV

      - name: Merge Firmware
        run: |
          esptool.py --chip esp32 merge_bin \
            -o merged-firmware.bin \
            --flash_mode dio \
            --flash_freq 40m \
            --flash_size 4MB \
            0x1000 ./build/05-WorkingLED.ino.bootloader.bin \
            0x8000 ./build/05-WorkingLED.ino.partitions.bin \
            0xe000 "${{ env.BOOT_APP0_PATH }}" \
            0x10000 ./build/05-WorkingLED.ino.bin
      
      - name: Save Artifact
        uses: actions/upload-artifact@v2
        with:
          name: merged-firmware
          path: merged-firmware.bin

      - run: cp merged-firmware.bin docs/

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'docs/'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4