name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/checkout@v4
        with:
          repository: 'mccahan/HomeSpan'
          path: libraries/HomeSpan

      - run: ls -l

      - uses: arduino/compile-sketches@v1
        with:
          fqbn: "esp32:esp32:esp32"
          verbose: true
          libraries: |
            - source-url: https://github.com/mccahan/HomeSpan.git
              name: HomeSpan
          sketch-paths: |
            - ./01-Sample-LightBulb/

      - run: pip install esptool
      - run: arduino-cli compile --fqbn esp32:esp32:esp32 ./01-Sample-LightBulb/